// Code generated by "stringer -type AttrFlag"; DO NOT EDIT.

package sftp

import "strconv"

const (
	_AttrFlag_name_0 = "SSH_FILEXFER_ATTR_SIZESSH_FILEXFER_ATTR_UIDGID"
	_AttrFlag_name_1 = "SSH_FILEXFER_ATTR_PERMISSIONS"
	_AttrFlag_name_2 = "SSH_FILEXFER_ATTR_ACMODTIME"
	_AttrFlag_name_3 = "SSH_FILEXFER_ATTR_EXTENDED"
)

var (
	_AttrFlag_index_0 = [...]uint8{0, 22, 46}
	_AttrFlag_index_1 = [...]uint8{0, 29}
	_AttrFlag_index_2 = [...]uint8{0, 27}
	_AttrFlag_index_3 = [...]uint8{0, 26}
)

func (i AttrFlag) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _AttrFlag_name_0[_AttrFlag_index_0[i]:_AttrFlag_index_0[i+1]]
	case i == 4:
		return _AttrFlag_name_1
	case i == 8:
		return _AttrFlag_name_2
	case i == 2147483648:
		return _AttrFlag_name_3
	default:
		return "AttrFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
