// Code generated by "stringer -type PacketType"; DO NOT EDIT.

package sftp

import "strconv"

const (
	_PacketType_name_0 = "SSH_FXP_INITSSH_FXP_VERSIONSSH_FXP_OPENSSH_FXP_CLOSESSH_FXP_READSSH_FXP_WRITESSH_FXP_LSTATSSH_FXP_FSTATSSH_FXP_SETSTATSSH_FXP_FSETSTATSSH_FXP_OPENDIRSSH_FXP_READDIRSSH_FXP_REMOVESSH_FXP_MKDIRSSH_FXP_RMDIRSSH_FXP_REALPATHSSH_FXP_STATSSH_FXP_RENAMESSH_FXP_READLINKSSH_FXP_LINKSSH_FXP_BLOCKSSH_FXP_UNBLOCK"
	_PacketType_name_1 = "SSH_FXP_STATUSSSH_FXP_HANDLESSH_FXP_DATASSH_FXP_NAMESSH_FXP_ATTRS"
	_PacketType_name_2 = "SSH_FXP_EXTENDEDSSH_FXP_EXTENDED_REPLY"
)

var (
	_PacketType_index_0 = [...]uint16{0, 12, 27, 39, 52, 64, 77, 90, 103, 118, 134, 149, 164, 178, 191, 204, 220, 232, 246, 262, 274, 287, 302}
	_PacketType_index_1 = [...]uint8{0, 14, 28, 40, 52, 65}
	_PacketType_index_2 = [...]uint8{0, 16, 38}
)

func (i PacketType) String() string {
	switch {
	case 1 <= i && i <= 22:
		i -= 1
		return _PacketType_name_0[_PacketType_index_0[i]:_PacketType_index_0[i+1]]
	case 101 <= i && i <= 105:
		i -= 101
		return _PacketType_name_1[_PacketType_index_1[i]:_PacketType_index_1[i+1]]
	case 201 <= i && i <= 202:
		i -= 201
		return _PacketType_name_2[_PacketType_index_2[i]:_PacketType_index_2[i+1]]
	default:
		return "PacketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
